[package]
name = "bevy_turtlebot4_testbed"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", features = ["wayland", "dynamic_linking", "jpeg"] }
bevy_eventlistener = { version = "0.7" }
bevy_rapier3d = { version = "0.25.0", features = ["debug-render-3d"] }
bevy_mod_picking = { version = "0.18.2", default-features = false, features = ["backend_rapier"] }
tracing = "0.1"
